### ISSUE TITLE
@peidrao can you do a rebase and a squash?

### ISSUE THREAD

**Issue by AdrianCert** [peidrao/peidrao#3]
@peidrao can you do a rebase and a squash?

_Originally posted by @AdrianCert in https://github.com/vinta/awesome-python/pull/2292#issuecomment-2143529809_

Please add me on the colaborator for your awesome-python fork. I want to rebase and quash all the commits! I suspect that the history is a reason for long pr!

**Comment by peidrao** [comment]
I replied to you over [there](https://github.com/vinta/awesome-python/pull/2292#issuecomment-2143865908)
